---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    compose_directory: /data/blockexchange.minetest.ch
  tasks:
    - name: Copy config files
      template:
        src: "{{item}}"
        dest: "{{compose_directory}}/{{item}}"
      with_items:
        - "docker-compose.yml"
        - "blockexchange.env"
        - "haproxy.cfg"

    - name: Update active deployment
      docker_compose:
        project_src: "{{ compose_directory }}"
        pull: yes
        services:
         - blockexchange_active

    - name: Wait for container start
      pause:
        seconds: 10

    - name: Update passive deployment
      docker_compose:
        project_src: "{{ compose_directory }}"
        pull: yes
        services:
         - blockexchange_passive

    - name: Start auxilliary services
      docker_compose:
        project_src: "{{ compose_directory }}"
        remove_orphans: yes
