---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    compose_directory: /data/blockexchange.minetest.ch
  tasks:
    - name: Copy config files
      template:
        src: "{{item}}"
        dest: "{{compose_directory}}/{{item}}"
      with_items:
        - "docker-compose.yml"
        - "blockexchange.env"
        - "haproxy.cfg"

    - name: Update active deployment
      shell:
        cmd: "docker-compose up -d blockexchange_active"
        chdir: "{{ compose_directory }}"
  
    - name: Wait for container start
      pause:
        seconds: 10

    - name: Update passive deployment
      shell:
        cmd: "docker-compose up -d blockexchange_passive"
        chdir: "{{ compose_directory }}"

    - name: Start auxilliary services
      shell:
        cmd: "docker-compose up -d --remove-orphans"
        chdir: "{{ compose_directory }}"
