version: "2"


services:
 blockexchange_blue:
  image: blockexchange/blockexchange
  restart: always
  depends_on:
   - postgres
  env_file:
   - blockexchange.env
  logging:
   options:
    max-size: 50m

 blockexchange_green:
  image: blockexchange/blockexchange
  restart: always
  depends_on:
   - postgres
  env_file:
   - blockexchange.env
  logging:
   options:
    max-size: 50m

 redis:
  image: redis:6.2.7-alpine
  restart: always

 postgres:
  image: postgres:14.2
  restart: always
  shm_size: '2gb'
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "./data/postgres:/var/lib/postgresql/data"
  command:
   - "postgres"
   - "-c"
   - "shared_buffers=4GB"
   - "-c"
   - "synchronous_commit=off"
  logging:
   options:
    max-size: 50m

 nginx:
  image: nginx:1.23.0
  networks:
   - terminator
   - default
  restart: always
  depends_on:
   - blockexchange_blue
   - blockexchange_green
  labels:
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.routers.blockexchange.rule=Host(`blockexchange.minetest.land`)"
    - "traefik.http.services.blockexchange.loadbalancer.server.port=80"
    - "traefik.http.routers.blockexchange.entrypoints=websecure"
    - "traefik.http.routers.blockexchange.tls.certresolver=default"
  volumes:
   - "./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
   - "./data/nginx/routes:/routes"
   - "./data/nginx/html:/html"
  logging:
   options:
    max-size: 50m

networks:
 terminator:
  external: true
