name: deploy

on:
  repository_dispatch:
    types: [deploy]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Prepare environment
      run: |
        id
        eval $(ssh-agent -s)
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan akheron.rudin.io >> ~/.ssh/known_hosts
        chmod -R 700 ~/.ssh
        ansible-galaxy collection install community.general
        echo "${{ secrets.VAULT_PASS }}" > ~/.vault_pass.txt
    - name: Run ansible
      run: |
        ansible-playbook -i hosts --vault-password-file ~/.vault_pass.txt --private-key ~/.ssh/id_rsa deploy.yml

    - name: 📧 Discord success notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.discord_webhook }}
      uses: Ilshidur/action-discord@0.3.2
      with:
        args: '☑️ Central blockexchange deployment updated'

    - name: curl
      uses: wei/curl@v1
      with:
        args: -H 'Title:\ blockexchange.minetest.ch' -H 'Tags:\ white_check_mark' -d 'Build succeeded for ${GITHUB_SHA}' ${{ secrets.NTFY_URL }}
