name: migrate-pg

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    concurrency: deployment
    steps:
    - uses: actions/checkout@v5
    - name: Prepare environment
      run: |
        id
        eval $(ssh-agent -s)
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan blockexchange.minetest.ch >> ~/.ssh/known_hosts
        chmod -R 700 ~/.ssh
        ansible-galaxy collection install community.general
        echo "${{ secrets.VAULT_PASS }}" > ~/.vault_pass.txt
    - name: Run ansible
      run: |
        ansible-playbook -i hosts --vault-password-file ~/.vault_pass.txt --private-key ~/.ssh/id_rsa migrate-pg.yml

    - name: 📧 Discord success notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.discord_webhook }}
      uses: Ilshidur/action-discord@0.4.0
      with:
        args: '☑️ Central blockexchange deployment updated'

    - name: ntfy success notification
      uses: wei/curl@v1
      with:
        args: -H "Title:blockexchange.minetest.ch" -H "Tags:white_check_mark" -d 'Build succeeded for ${{github.sha}}' ${{ secrets.NTFY_URL }}

    - name: ntfy failure notification
      if: failure()
      uses: wei/curl@v1
      with:
        args: -H "Title:blockexchange.minetest.ch" -H "Tags:warning" -d 'Build failed for ${{github.sha}}' ${{ secrets.NTFY_URL }}
